[package]
name = "learn-ratatui-app_patterns"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.88"
ratatui = "0.28.1"
edtui = "0.7.2"

raalog = { path = "../raalog" }
# raalog = { git = "https://github.com/AlexanderARodin/raalog.git", branch = "main" }
